### ISSUE TITLE
Make this a template repo

### ISSUE THREAD

**Issue by szepeviktor** [owenvoke/skeleton-php#23]
![kép](https://user-images.githubusercontent.com/952007/83407609-61c63380-a411-11ea-9d86-ca33de43e22a.png)

A picture is worth a thousand words

**Comment by owenvoke** [comment]
Hey, done now. 👍 I thought I'd already done that, so thanks for pointing it out.

Really wish GitHub templates supported placeholders though so I could get rid of the `prefill.php` maybe I'll just do that anyway.

**Comment by szepeviktor** [comment]
You're welcome.
